name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - seaborn=0.11.2
  - pip=22.1.2
  - pandas=1.4.4
  - pandas-profiling=3.2.0
  - fastparquet=0.8.3
  - pyarrow=8.0.0
  - pip:
    - wandb==0.13.2